import { ORDER_STATUS } from '../../../enums/order';

// Allowed forward transitions for each order status.
export const ORDER_STATUS_TRANSITIONS: Record<ORDER_STATUS, ORDER_STATUS[]> = {
  [ORDER_STATUS.PENDING_PAYMENT]: [ORDER_STATUS.SECURED],
  [ORDER_STATUS.SECURED]: [
    ORDER_STATUS.COLLECTION_PENDING,
    ORDER_STATUS.COLLECTED,
    ORDER_STATUS.CANCELLED,
  ],
  [ORDER_STATUS.COLLECTION_PENDING]: [ORDER_STATUS.COLLECTED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.COLLECTED]: [
    ORDER_STATUS.VERIFICATION,
    ORDER_STATUS.PAYOUT_PROCESSING,
    ORDER_STATUS.REFUNDED,
  ],
  [ORDER_STATUS.VERIFICATION]: [ORDER_STATUS.PAYOUT_PROCESSING, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.PAYOUT_PROCESSING]: [ORDER_STATUS.READY_FOR_DELIVERY],
  [ORDER_STATUS.READY_FOR_DELIVERY]: [
    ORDER_STATUS.DELIVERED,
    ORDER_STATUS.REFUNDED,
  ],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.COMPLETED]: [],
  [ORDER_STATUS.REFUNDED]: [],
  [ORDER_STATUS.CANCELLED]: [],
};

// Statuses that, once entered, trigger an automatic Stripe refund + relist the product.
export const REFUND_TRIGGER_STATUSES: ORDER_STATUS[] = [
  ORDER_STATUS.REFUNDED,
  ORDER_STATUS.CANCELLED,
];
